### ISSUE TITLE
rviz not included in current builds

### ISSUE THREAD

**Issue by chrismbirmingham** [interaction-lab/HARMONI#30]
```[INFO] [1603080446.854993]: Average audio intensity is 1
[INFO] [1603080446.855135]: Silence threshold set to 5
[INFO] [1603080446.858381]: Sucessfully reached microphone_default
[INFO] [1603080446.858739]: Service Server microphone_default has been successfully set up
[INFO] [1603080446.872074]: HardwareControlServer start continuously updating the feedback
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
2020-10-18 21:07:27-0700 [-] WebSocketServerFactory starting on 9090
2020-10-18 21:07:27-0700 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7fa548dfaa90>
2020-10-18 21:07:27-0700 [-] [INFO] [1603080447.035514]: Rosbridge WebSocket server started at ws://0.0.0.0:9090
[INFO] [1603080447.203762]: Rosapi started
process[harmoni_speaker_default-6]: started with pid [210]
[INFO] [1603080447.796149]: Initializing the speaker_default service
[INFO] [1603080447.798399]: Sucessfully reached speaker_default
[INFO] [1603080447.798603]: Service Server speaker_default has been successfully set up
[INFO] [1603080447.811907]: HardwareControlServer start continuously updating the feedback
process[audio/audio_play-7]: started with pid [224]

** (audio_play:224): CRITICAL **: file gstaudioringbuffer.c: line 1971 (gst_audio_ring_buffer_set_channel_positions): should not be reached
process[harmoni_gesture_default-8]: started with pid [241]
[INFO] [1603080448.835374]: Initializing the gesture_default service
[INFO] [1603080448.841293]: Setting up the gesture_default
process[harmoni_gesture_qt_default-9]: started with pid [254]
[INFO] [1603080449.417943]: Initializing the gesture_default_qt service
process[joint_state_publisher-10]: started with pid [268]
process[robot_joint_state_publisher_default-11]: started with pid [297]
[INFO] [1603080450.573871]: Initializing the gesture_default_qt_simulator service
process[robot_state_publisher-12]: started with pid [306]
process[rviz-13]: started with pid [328]
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
================================================================================REQUIRED process [rviz-13] has died!
process has died [pid 328, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /opt/ros/kinetic/share/urdf_tutorial/rviz/urdf.rviz __name:=rviz __log:=/root/.ros/log/8e9eaeba-11c0-11eb-adbe-0242ac120304/rviz-13.log].
log file: /root/.ros/log/8e9eaeba-11c0-11eb-adbe-0242ac120304/rviz-13*.log
Initiating shutdown!
================================================================================
[rviz-13] killing on exit
[robot_state_publisher-12] killing on exit
[robot_joint_state_publisher_default-11] killing on exit
[joint_state_publisher-10] killing on exit
[harmoni_gesture_qt_default-9] killing on exit
[harmoni_gesture_default-8] killing on exit
[audio/audio_play-7] killing on exit
[harmoni_speaker_default-6] killing on exit
[bridge_face/rosapi-5] killing on exit
[bridge_face/rosbridge_websocket-4] killing on exit
[harmoni_face_default-3] killing on exit
2020-10-18 21:07:31-0700 [autobahn.twisted.websocket.WebSocketServerFactory] (TCP Port 9090 Closed)
2020-10-18 21:07:31-0700 [-] Stopping factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7fa548dfaa90>
2020-10-18 21:07:31-0700 [-] Main loop terminated.
[face_http_server-2] killing on exit
http-server stopped.
[harmoni_microphone_default-1] killing on exit
[harmoni_gesture_default-8] escalating to SIGTERM
Traceback (most recent call last):
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/scripts/harmoni_gesture/gesture_service.py", line 179, in <module>
    main()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/scripts/harmoni_gesture/gesture_service.py", line 164, in main
    s = GestureService(service, param)
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/scripts/harmoni_gesture/gesture_service.py", line 49, in __init__
    self.setup_gesture()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/scripts/harmoni_gesture/gesture_service.py", line 73, in setup_gesture
    rospy.sleep(0.1)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 134, in sleep
    rospy.rostime.wallsleep(duration)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/rostime.py", line 277, in wallsleep
    time.sleep(duration) 
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 504, in _ros_signal
    prev_handler(sig, stackframe)
TypeError: 'Handlers' object is not callable
shutting down processing monitor...
... shutting down processing monitor complete
done```

**Comment by chrismbirmingham** [comment]
It looks like the the issue is specific to running rviz on machines with a nvidia gpu.

**Comment by micolspitale93** [comment]
Did you run `export DISPLAY=:0` before running the harmoni hardware services?

**Comment by RMichaelSwan** [comment]
Details on Nvidia issue: https://github.com/diegoferigo/dockerfiles/issues/6#issuecomment-457301619 , https://developer.nvidia.com/blog/gpu-containers-runtime/. 

There are some other alternatives as well: https://github.com/osrf/rvizweb , but this will take some work to getting running.

**Comment by chrstrom** [comment]
Hi, I ran into a similar issue when running RViz in a docker container on a Windows host, and fixed it by adding the -nowgl argument when launching the X11 session, and setting LIBGL_ALWAYS_INDIRECT=0 in the container. Not sure if it applies here, but potentially worth checking out 😄

**Comment by chrismbirmingham** [comment]
The issue no longer appears to be with rviz, but with some dependencies on Noetic. Closing this issue in favor of #84
