### ISSUE TITLE
Gesture Test Failing

### ISSUE THREAD

**Issue by chrismbirmingham** [interaction-lab/HARMONI#51]
```
[ROSUNIT] Outputting test results to /root/.ros/test_results/harmoni_gesture/rostest-test_gesture.xml
[INFO] [1621439158.279799]: Initializing the gesture service
[INFO] [1621439158.284864]: Setting up the gesture
[INFO] [1621439158.787637]: Initializing the gesture_qt service
[INFO] [1621439159.718419]: Initializing the gesture service
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/src/harmoni_gesture/gesture_service.py", line 239, in <module>
    main()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/src/harmoni_gesture/gesture_service.py", line 230, in main
    s = GestureService(service_name, params)
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/src/harmoni_gesture/gesture_service.py", line 48, in __init__
    self.setup_gesture()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/src/harmoni_gesture/gesture_service.py", line 79, in setup_gesture
    rospy.sleep(0.1)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 134, in sleep
    rospy.rostime.wallsleep(duration)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/rostime.py", line 277, in wallsleep
    time.sleep(duration) 
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 504, in _ros_signal
    prev_handler(sig, stackframe)
TypeError: 'Handlers' object is not callable
[Testcase: testtest_gesture] ... ok

[ROSTEST]-----------------------------------------------------------------------

[harmoni_gesture.rosunit-test_gesture/test_request_response][ERROR]-------------
init_node interrupted before it could complete
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 601, in run
    self.setUp()
  File "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_gesture/test/rostest_gesture.py", line 28, in setUp
    rospy.init_node("test_gesture", log_level=rospy.INFO)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 323, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 1
 * FAILURES: 0

rostest log file is in /root/.ros/log/rostest-harmoni_full-3306.log
```

**Comment by chrismbirmingham** [comment]
This test works in the latest builds.
